<?php
namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class LotteryFactory extends Factory
{
    protected $model = \App\Models\admin\Lottery::class;

    public function definition(): array
    {
        return [
            'title' => $this->faker->sentence(3),
            'description' => $this->faker->paragraph,
            'ticket_price' => $this->faker->randomFloat(2, 10, 1000),
            'total_tickets' => $this->faker->numberBetween(50, 1000),
            'number_of_winners' => $this->faker->numberBetween(1, 10),
            'draw_datetime' => $this->faker->dateTimeBetween('+1 days', '+1 month'),
            // 'tid' will be auto-generated by your model boot() method
        ];
    }
}
